[phases]
setup = "apt-get update && apt-get install -y wget unzip"
install = """
wget https://github.com/v2fly/v2ray-core/releases/download/v5.12.1/v2ray-linux-64.zip
unzip v2ray-linux-64.zip
cp v2ray /usr/local/bin/
cp v2ctl /usr/local/bin/
"""

[start]
command = "v2ray run -config=/etc/v2ray/config.json"